### PR TITLE
Fixed spl_object_hash collisions using internal attribute.

### LINKED ISSUE #23: Attributes are duplicated multiple nodes
There is very specific case when attributes from two nodes are merged together. Interesting is that if you remove div with class xxx, it will start working again.

My code:
```php
$twigLoader = new Goetas\Twital\TwitalLoader(new \Twig_Loader_String()); //new \TwitalLoader(new \Twig_Loader_String());
$twigLoader->addSourceAdapter('/.*/', new Goetas\Twital\SourceAdapter\HTML5Adapter());
$twig = new Twig_Environment($twigLoader, ['cache' => false, 'autoescape' => true]);

$source = <<<EOT
                   <t:omit> <ol style="opc">
            <li t:attr="true ? style='display:none'"></li>
        </ol>
        <div class="xxx"> <span class="abc">yyy</span></div>

        <div class='qqq'>
            <input type='checkbox' t:attr="true ? checked='checked'">

        </div>
        </t:omit>
EOT;

print_r($twig->loadTemplate($source)->render([]));
```

Expected result:
```html
<ol style="opc">
            <li style="display:none"></li>
        </ol>
        <div class="xxx"> <span class="abc">yyy</span></div>

        <div class="qqq">
            <input type="checkbox" checked="checked">

        </div>
```

Actual result:
```html
<ol style="opc">
            <li style="display:none"></li>
        </ol>
        <div class="xxx"> <span class="abc">yyy</span></div>

        <div class="qqq">
            <input type="checkbox" style="display:none" checked="checked">

        </div>
```

Both LI and INPUT have display:none but it was defined only for LI.

I looked into php cache of template file a there is the same key used for both nodes (__a9000000006d37f06100007f887925bc9c). My guess is that problem is in spl_object_hash which is used for keys:
*When an object is destroyed, its hash may be reused for other objects.*
https://php.net/spl_object_hash

### PR DESCRIPTION
**Pull request by goetas**
Fixes #23 

Test suite is still missing

### CODE REVIEW

File: src/Goetas/Twital/Attribute/AttrAttribute.php [hunk 1]
```diff
@@ -13,9 +14,9 @@
  */
 class AttrAttribute implements Attribute
 {
-    public static function getVarname(\DOMNode $node)
+    public static function getVarname(\DOMElement $node)
     {
-        return "__a9" . strtr(md5($node->ownerDocument->saveXML($node)).spl_object_hash($node), "-","_");
+        return "__a9" . strtr($node->getAttributeNS(Twital::NS, '__internal-id__').spl_object_hash($node), "-","_");
```
Comment (soukiii) [inline src/Goetas/Twital/Attribute/AttrAttribute.php]: Wasn't the whole point of this to replace spl_object_hash with some unique key? Or maybe I just don't understand how it works now.

Comment (soukiii) [inline src/Goetas/Twital/Attribute/AttrAttribute.php]: Oh, I get it now. First part of hash is unique for current document and second part ensures that it won't colide with normal variables.

Comment (goetas) [inline src/Goetas/Twital/Attribute/AttrAttribute.php]: It is also possible to create plugins that are able to "clone" dom nodes. Cloning a node, the `__internal-id__` will remain untouched, so using both `spl_object_hash` and `__internal-id__` the node identifier "should" be more reliable.

File: src/Goetas/Twital/EventSubscriber/IDNodeSubscriber.php [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    }
+
+    public function addAttribute(TemplateEvent $event)
+    {
+        $doc = $event->getTemplate()->getDocument();
+        $xp = new \DOMXPath($doc);
+        $nodes = $xp->query("//*[@*[namespace-uri()='".Twital::NS."']]");
+        $cnt = 0;
+        foreach ($nodes as $node) {
+            $node->setAttributeNS(Twital::NS, '__internal-id__', ++$cnt);
```
Comment (goetas) [inline src/Goetas/Twital/EventSubscriber/IDNodeSubscriber.php]: > @soukiii Oh, I get it now. First part of hash is unique for current document and second part ensures that it won't colide with normal variables.

My first idea was to assign a random string instead of `++$cnt`. Doing this I will be more safe with multiple documents... What is your opinion about this?

Comment (soukiii) [inline src/Goetas/Twital/EventSubscriber/IDNodeSubscriber.php]: `$cnt` is unique only in scope of one document. Consider this two templates:

```
{# one.twig #}
<input t:attr="true ? class='X'">
{% include "two.twig" %}
```

```
{# two.twig #}
<input t:attr="true ? class='Y'">
```

There will be `$cnt==1` in each but twig variable from *one* will be readable in *two*. It won't help to have static counter because cache for each file can be created in different time.

Comment (goetas) [inline src/Goetas/Twital/EventSubscriber/IDNodeSubscriber.php]: What about using here `uniqid` ?

Comment (goetas) [inline src/Goetas/Twital/EventSubscriber/IDNodeSubscriber.php]: > It won't help to have static counter because cache for each file can be created in different time.
There is not need to have globally unique id, most probably twig "scope" will avoid collisions in this case

Comment (soukiii) [inline src/Goetas/Twital/EventSubscriber/IDNodeSubscriber.php]: > What about using here uniqid ?

Simple `rand`might be better in this case. If uniqid is called fast enough, it will return the same id. There could also be md5 from uniqid, rand and spl_object_hash, but it would probably be overkill :)

Comment (goetas) [inline src/Goetas/Twital/EventSubscriber/IDNodeSubscriber.php]: > If uniqid is called fast enough, it will return the same id

Really? Is it documented somewhere?
